### ISSUE TITLE
Timestamp from .FIT files 

### ISSUE THREAD

**Issue by josebadoe** [jmackie4/activityio#1]
Hi! In fit/_reading.py the "DATETIME_1990 = datetime(year=1990, month=1, day=1)", used as epoch for timestamps causes the incorrect date to be returned in the timestamp. The correct value would be datetime(year=1989, month=12, day=31).

If you want a .fit file for testing, or a patch (or a pull request), just let me know.

**Comment by jmackie** [comment]
Cheers bud, brain fart by me. Fixed with 643f025.
