### ISSUE TITLE
Time format in .TCX files

### ISSUE THREAD

**Issue by josebadoe** [jmackie4/activityio#2]
Hi! In tcx/_reading.py the DATETIME_FMT = '%Y-%m-%dT%H:%M:%S.%fZ' causes an error on the tcx files I get from a garmin edge 705. The XML schema http://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd defines the Time field with type="xsd:dateTime" and it's format is show (on http://books.xmlschemata.org/relaxng/ch19-77049.html) as  [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm], with Z being UTC and +/-NN being the offset from UTC in hours (and optionally in minutes), though according to garmin, all times are stored in UTC.

The definitions don't seem to allow fractional seconds, and in my files there sure are none present. So at least with my files the format DATETIME_FMT = '%Y-%m-%dT%H:%M:%SZ' works much better.

If you need file sample, patch, or pull request, just say so.

**Comment by jmackie** [comment]
Good catch, fixed in 11c20d9.
