### ISSUE TITLE
help missing documentation and file for tests

### ISSUE THREAD

**Issue by drr00t** [jmackie4/activityio#3]
Hi,

I like very much of your library and i would like to help us... i start to looking with my own garmin tcx activity exported files but i have some difficult to learn how to use the library to extract the values that i need, ex: 
* how can i get total distance, i tried data.dist[-1] but my garmin file has a NaN in the last line so this way don't work. I not cleanup the file yet, so i have a few Nans

02:37:03 	142.0 	1138.400024 	21043.250000 	-15.839027 	1.152 	-48.023138
02:37:11 	142.0 	1138.599976 	21050.830078 	-15.839044 	0.948 	-48.023208
02:37:14 	NaN 	1138.599976 	NaN 	NaN 	0.000 	NaN

* how can i get the pace?

just i case, if you get me some directions i can write the tests for library and may be i can release one of my track file so we can automate the tests. I run and my longest activity was a half-marathon.

What you think about?

greate work.

**Comment by jmackie** [comment]
The distance column is cumulative, so you're looking for: `max(data.dist)` or just `data.dist.max()`.

For pace: `data.speed.to_pace()` (see [here](https://github.com/jmackie4/activityio/blob/master/activityio/_types/columns.py))

I will add more documentation when I get the time, as well as deploy with some tests. I have tests that run on my local machine, but a lot of the files I have aren't my own, hence I can't commit them here. If you want to compress some of your *.tcxs file and email them across to me I can start to build up a file bank.

With regards to documentation, this package is very much an extension of the `numpy`/`pandas` ecosystem. If you haven't already, [read this](http://shop.oreilly.com/product/0636920023784.do).
